version: '3'
services:
  redis:
    image: redis:latest
    ports:
      - '6379:6379'

  mysql:
    image: mysql:8
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: rate_limiting
    ports:
      - '3306:3306'

  redisinsight:
    image: redis/redisinsight
    ports:
      - '5540:5540'
