name: Hello World

on:
  push:

jobs:
  greet:
    runs-on: ubuntu-latest
    steps:
      - name: Dire bonjour
        run: echo "Hello, GitHub Actions!"

      - name: Date et heure
        run: date
